<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Terms of Service — Nivaya Life</title>

    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700,800&display=swap" rel="stylesheet">

    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-novix-cream font-sans text-novix-ink antialiased dark:bg-novix-night dark:text-novix-cream">

    <header class="border-b border-novix-green/10 bg-novix-cream/90 backdrop-blur dark:bg-novix-night/90">
        <div class="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
            <a href="/" class="flex items-center gap-2" aria-label="Nivaya Life home">
                <x-novix-logo size="sm" />
            </a>
            <a href="{{ url('/privacy') }}" class="text-sm font-medium text-novix-green hover:underline">Privacy Policy</a>
        </div>
    </header>

    <main class="mx-auto max-w-3xl px-6 py-12">
        <h1 class="text-3xl font-extrabold text-novix-ink dark:text-white">Terms of Service</h1>
        <p class="mt-2 text-sm text-novix-muted">Last updated {{ now()->format('F j, Y') }}</p>

        <div class="mt-10 space-y-10 text-sm leading-relaxed text-novix-ink/90 dark:text-white/80">

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">1. Agreement to these terms</h2>
                <p class="mt-2">By creating an account or otherwise using Nivaya Life ("the Service," "we," "us"), you agree to these Terms of Service and our <a href="{{ url('/privacy') }}" class="text-novix-green underline">Privacy Policy</a>. If you do not agree, do not use the Service.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">2. What Nivaya Life is</h2>
                <p class="mt-2">Nivaya Life is a personal and family health-records application. It lets you upload and organize medical documents (prescriptions, lab reports, imaging, discharge summaries, and similar records), automatically extracts and summarizes their content using optical character recognition (OCR) and AI, tracks medications and vaccinations with reminders, and lets you share records with family members or other people you choose.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">3. Not medical advice</h2>
                <p class="mt-2">Nivaya Life is a record-keeping and organizational tool. Nothing generated by the Service — including AI-written summaries, explanations, translations, extracted lab values, or the Assistant chat — is medical advice, a diagnosis, or a substitute for care from a qualified healthcare professional. Automated summaries and AI output can be incomplete or wrong, including because of imperfect OCR or AI misinterpretation of a document. Always verify anything important against the original document and consult a doctor before making any medical decision.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">4. Your account</h2>
                <p class="mt-2">You must provide accurate information when creating an account and are responsible for keeping your login credentials secure and for all activity under your account. You must be legally able to consent to these terms in your jurisdiction to register your own account; a parent or guardian may add a child or other dependent as a family member under their own account.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">5. Acceptable use</h2>
                <p class="mt-2">You agree not to: upload content that isn't genuinely health-related documentation for yourself or someone you're authorized to manage records for; use the Service to store or share unlawful content; attempt to access another person's account or records without authorization; interfere with or disrupt the Service's operation; or use the Service in any way that violates applicable law.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">6. Your content</h2>
                <p class="mt-2">You retain ownership of the documents and information you upload. By uploading content, you grant Nivaya Life a limited license to store, process, and display that content solely to provide the Service to you and anyone you explicitly share it with. We do not sell your health data or use it for advertising.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">7. AI and third-party processing</h2>
                <p class="mt-2">To generate summaries, translations, and extracted data, uploaded documents or the text extracted from them may be sent to third-party AI providers (currently Google Gemini and Groq) and to OCR/analysis services we operate. This processing happens automatically as part of using the Service. See our <a href="{{ url('/privacy') }}" class="text-novix-green underline">Privacy Policy</a> for details on what's shared and with whom.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">8. Family sharing and access</h2>
                <p class="mt-2">You can add family members to your account and grant other people access to specific records via the sharing and invitation features. You are responsible for only sharing records with people you intend to have access, and for managing or revoking access when appropriate.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">9. Reminders and notifications</h2>
                <p class="mt-2">Medication and vaccination reminders (by email and, if enabled, push notification) are provided for convenience only. They are not a guaranteed or medically supervised alerting system, and Nivaya Life is not responsible for missed doses, delivery failures, or any consequence of relying on a reminder instead of your own judgment or your healthcare provider's instructions.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">10. Account deletion and data retention</h2>
                <p class="mt-2">You may delete your account at any time from Profile → Account Security. Doing so immediately removes your profile, reports, and data from active use, and signs you out everywhere. For recovery and audit purposes, a record of the deleted data is retained internally rather than being immediately and permanently erased. If you create a new account later with the same email address, it starts as a completely new, unrelated account — deleted data is not restored to it. See our <a href="{{ url('/privacy') }}" class="text-novix-green underline">Privacy Policy</a> for more detail.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">11. Suspension and termination</h2>
                <p class="mt-2">We may suspend or terminate access to the Service for anyone who violates these terms, misuses the Service, or where required by law. You may stop using the Service and delete your account at any time.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">12. Disclaimers and limitation of liability</h2>
                <p class="mt-2">The Service is provided "as is" and "as available," without warranties of any kind, express or implied. To the fullest extent permitted by law, Nivaya Life and its operators are not liable for any indirect, incidental, or consequential damages, or for any medical, financial, or other decision made in reliance on information stored in or generated by the Service. Nothing in these terms limits liability that cannot legally be limited.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">13. Changes to these terms</h2>
                <p class="mt-2">We may update these terms from time to time. Continued use of the Service after a change takes effect constitutes acceptance of the updated terms.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">14. Governing law</h2>
                <p class="mt-2">These terms are governed by the laws of India, without regard to conflict-of-law principles.</p>
            </section>

            <section>
                <h2 class="text-lg font-bold text-novix-ink dark:text-white">15. Contact</h2>
                <p class="mt-2">Questions about these terms can be sent to <a href="mailto:support@novix.app" class="text-novix-green underline">support@novix.app</a>.</p>
            </section>

        </div>

        <a href="/" class="mt-12 inline-block text-sm font-semibold text-novix-green hover:underline">&larr; Back to Nivaya Life</a>
    </main>

</body>
</html>
